model:
  base_learning_rate: 9.e-06
  target: ldm.models.autoencoder.VQModel
  params:
    embed_dim: 256
    n_embed: 1024
    image_key: 0
    ddconfig:
      double_z: false
      z_channels: 64
      resolution: 128
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    lossconfig:
      target: ldm.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 5000000
        disc_weight: 0.5
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    wrap: True
    train:
      target: ldm.data.GENS_handler.ISData_Loader_train
    validation:
      target: ldm.data.GENS_handler.ISData_Loader_val

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  modelcheckpoint:
      every_n_epochs: 200
      save_last: True

  trainer:
    benchmark: True
    accelerator: ddp
    max_epochs: 30000