model:
  base_learning_rate: 5.0e-06
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: val/rec_loss
    embed_dim: 3
    image_key: 0
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50000000000
        kl_weight: 1.0e-06
        disc_weight: 0.5
    ddconfig:
      double_z: true
      z_channels: 3
      resolution: 128
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    wrap: true
    train:
      target: ldm.data.GENS_handler.ISData_Loader_train
    validation:
      target: ldm.data.GENS_handler.ISData_Loader_val
