model:
  base_learning_rate: .5e-5
  target: ldm.models.autoencoder.VQModel
  params:
    embed_dim: 64
    n_embed: 256
    image_key: 0
    ddconfig:
      double_z: False
      z_channels: 128
      resolution: 128
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: ldm.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 5000000000000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    wrap: True
    train:
      target: ldm.data.GENS_handler.ISData_Loader_train
    validation:
      target: ldm.data.GENS_handler.ISData_Loader_val

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  modelcheckpoint:
      every_n_epochs: 200
      save_last: True

  trainer:
    benchmark: True
    accelerator: ddp
    max_epochs: 30000