model:
  base_learning_rate: 1.e-06
  target: ldm.models.autoencoder.VQModel
  params:
    embed_dim: 4 # must be = to z_channels
    n_embed: 16384 
    image_key: 0
    ddconfig:
      double_z: false
      z_channels: 4
      resolution: 128
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 32
      dropout: 0.0
    lossconfig:
      target: ldm.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_num_layers: 2
        disc_start: 330000
        disc_weight: 0.1
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    wrap: True
    train:
      target: ldm.data.GENS_handler.ISData_Loader_train
    validation:
      target: ldm.data.GENS_handler.ISData_Loader_val

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True        
        log_images_kwargs:
          uvt: True

  modelcheckpoint:
    params:
      every_n_epochs: 50
      save_last: True
      save_top_k: True

  trainer:
    benchmark: True
    accelerator: ddp
    max_epochs: 30000