model:
  base_learning_rate: 5.e-5
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: 0
    image_size: 32
    channels: 3 # same as autoencoder z_channel 
    monitor: val/loss_simple_ema

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 3 # same as autoencoder z_channel
        out_channels: 3 # same as autoencoder z_channel
        model_channels: 224
        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_head_channels: 32
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3 # must be = to z_channels
        n_embed: 8192
        image_key: 0
        ckpt_path: models/first_stage_models/gens_LD_vqgan_fl4_D3_N8192_32x32x3/2199-v1_cyclic_tri2_mlr5-5.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 128
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_unconditional__


    # scheduler_config:
    #   target: torch.optim.lr_scheduler.CyclicLR
    #   params:
    #     base_lr: 1.e-6
    #     max_lr: 5.e-5
    #     step_size_up: 1000
    #     mode: triangular     
    #     cycle_momentum: False


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 96 #128
    wrap: True
    train:
      target: ldm.data.GENS_handler.ISData_Loader_train
    validation:
      target: ldm.data.GENS_handler.ISData_Loader_val

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: True
        log_images_kwargs:
          uvt: True

  modelcheckpoint:
    params: 
      every_n_epochs: 50
      save_last: True
      save_top_k: 5



  trainer:
    benchmark: True
    accelerator: ddp
    max_epochs: 30000
    # strategy: "ddp_find_unused_parameters_false"