model:
  base_learning_rate: 1.e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0001
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: 0
    image_size: 16
    channels: 256
    monitor: val/loss_simple_ema

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 16
        in_channels: 256
        out_channels: 256
        model_channels: 224
        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_head_channels: 32
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 256
        n_embed: 1024
        image_key: 0
        ckpt_path: models/first_stage_models/gens_LD_vqgan_fl8_D256_N1024_16x16/878.ckpt
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 128
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_unconditional__

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 64
    num_workers: 128
    wrap: True
    train:
      target: ldm.data.GENS_handler.ISData_Loader_train
    validation:
      target: ldm.data.GENS_handler.ISData_Loader_val

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: True

  modelcheckpoint:
      every_n_epochs: 200
      save_last: True

  trainer:
    benchmark: True
    accelerator: ddp
    max_epochs: 30000
    strategy: "ddp_find_unused_parameters_false"